# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hyperledger Caliper
description: >- # this means to ignore newlines until "baseurl:"
  Caliper is a blockchain performance benchmark framework, which allows users to test different blockchain solutions with predefined use cases, and get a set of performance test results.

url       : https://hyperledger.github.io # the base hostname & protocol for the site
baseurl   : /caliper # the subpath of the site, represents version in this example repo
repository: hyperledger/caliper # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
repo      : caliper

caliper:
  current_release: vLatest
  next_release: vNext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
categories: [docs]

collections:
  docs:
    output: true
    permalink: '/:collection/:path/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
