name: ci

on:
  push:
    # Publish `main` as latest
    branches:
      - main

    # Publish `v1.2.3` tags as releases
    tags:
      - v*

permissions:
  contents: write

jobs:
  deploy:
    permissions:
        pages: write
        id-token: write
        contents: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits/branches
#      - name: Checkout repo
#        run: |
#          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/davidkel/test-calip $GITHUB_WORKSPACE
      - name: Configure git user and test access
        run: |
          cat .git/config
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "new data" >> newfile.txt
          echo "adding changed files"
          git add .
          echo "committing"
          git commit -m "a new commit"
          echo "pushing"
          git push origin HEAD:main
#          echo "https://x-access-token:1234@github.com" > ~/.git-credentials
#          git config --global credential.helper store
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Python dependencies
        run: pip install -r ./docs/pip-requirements.txt
      - name: Deploy docs
        run: |
          # Strip git ref prefix from version
          echo "${{ github.ref }}"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && ALIAS=$(echo $VERSION | sed -e 's/^v//')
          # If building from main, use vNext as ALIAS
          [ "$VERSION" == "main" ] && ALIAS=vNext
          echo $VERSION $ALIAS
          cd docs
          mike delete --all
          mike deploy --push --update-aliases $ALIAS
          mike set-default vNext --push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
