name: Unit Tests

on:
  workflow_call:

env:
  NPM_VERSION: 8.15.0

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install higher version of NPM
      run: npm install -g npm@${{ env.NPM_VERSION }}
    - name: Check correct usage of Caliper package names
      run: ./scripts/check-package-names.sh
    - name: Install project dependencies
      run: npm ci
    - name: Check the version consistency of subpackages
      run: ./packages/caliper-publish/publish.js version check
    - name: Run unit tests
      run: npm test --workspaces
