---
blockchain:
  type: fabric
  config: benchmark/simple/fabric.json
command:
  start: docker-compose -f network/fabric/2org2peer/docker-compose.yaml up -d
  end: docker-compose -f network/fabric/2org2peer/docker-compose.yaml down;docker
    rm $(docker ps -aq);docker rmi $(docker images dev* -q)
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    txNumber:
    - 1000000
    rateControl:
    - type: fixed-feedback-rate
      opts:
        tps: 2000
        sleep_time: 50
        unfinished_per_client: 100
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
